name: mobile

description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

  #DI
  get_it: ^7.4.0
  injectable: ^2.1.1

  #State Management
  flutter_bloc: ^8.1.2

  #UI
  flutter_screenutil: ^5.7.0
  pin_code_fields: ^7.4.0
  smooth_page_indicator: ^1.1.0

  #Utils
  dartz: ^0.10.1
  go_router: ^7.0.0
  equatable: ^2.0.5

  #Annotations
  freezed_annotation: ^2.2.0

  #Network
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^3.0.6
  dio: ^5.1.1
  easy_logger: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.0
  injectable_generator: ^2.1.5
  freezed: ^2.3.3
  auto_route_generator: ^6.2.0
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/png/
    - config/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
